### ISSUE TITLE
lastUpdate in milliseconds instead of seconds

### ISSUE THREAD

**Issue by HazemKhaled** [Knawat/dropshipping-woocommerce#146] opened 2020-10-15 11:18 UTC
Currently, updating products accept seconds or milliseconds

1. We need to move to milliseconds instead for more accurate sync

https://docs.knawat.io/#tag/My-Products/paths/~1catalog~1products/get

![image](https://user-images.githubusercontent.com/125433/96112712-c16a3a80-0eeb-11eb-98b7-ddc7f4d86f71.png)

2. We need to sort by updated instead of created (default)
![image](https://user-images.githubusercontent.com/125433/96116526-460b8780-0ef1-11eb-9895-c57aae93104f.png)

**Comment by suraj-rathod** [comment] 2021-03-23 04:52
@HeshamIsmail Please test it

**Comment by HeshamIsmail** [comment] 2021-04-06 08:14
Our test on postman led for the following:

1.The get products request is pulling the right products within the right lastupdate date using a millisecond timestamp:
2.The field parameter is set to created as required above.

![image](https://user-images.githubusercontent.com/74185849/113679375-5f370900-96c8-11eb-9556-a7e68c8c89a7.png)

However, we noticed that the default value for lastupdate parameter is negative as below:

![image](https://user-images.githubusercontent.com/74185849/113680014-16cc1b00-96c9-11eb-8337-f483e42ea08f.png)

Please confirm if it's by design to accept negative values or not @suraj-rathod @iamdharmesh

**Comment by HeshamIsmail** [comment] 2021-04-16 08:02
Import function is now working as supposed, closing this issue.

**Closed by HeshamIsmail** 2021-04-16 08:02 UTC
Labels: bug
