### ISSUE TITLE
Add Sync Bar and Reset Sync Button

### ISSUE THREAD

**Issue by hamusthekiller** [Knawat/dropshipping-woocommerce#137] opened 2020-10-06 13:37 UTC
We need to show store owners the sync bar in their stores with the last updated import time and Add a button to reset that time and reflect the output on the sync bar.

### Acceptance criteria
1. In settings page show the following progress bar showing how many products he has and how many need to be synced
2. Sync All should reset last sync date, so next sync job should start from the beginning
![image](https://user-images.githubusercontent.com/125433/96115827-3a6b9100-0ef0-11eb-81a1-4718d1fa7eed.png)

**Comment by iamdharmesh** [comment] 2020-12-03 12:39
Ready for test @HeshamIsmail

**Comment by HeshamIsmail** [comment] 2020-12-03 14:17
Hello @suraj-rathod , 

In order to debug your issue, I want to know more info. Also, there could be some conflicts with other WordPress plugins. Could you disable all the plugins leaving only the Knawat plugin, and check if everything is working? If not provide me with detailed steps to reproduce the issue.

**Comment by HeshamIsmail** [comment] 2020-12-11 11:58
Test subject:

Sync bar:

Acceptance criteria

1. In settings page show the following progress bar showing how many products he has and how many need to be synced
2. Sync All should reset last sync date, so next sync job should start from the beginning

Testing steps:

1-Imported 9 products.

Result: Sync bar is highlighted green in full and count 9 products synched.
No last sync date was included

2-Click on Sync all 

Result: Sync bar not reset, still counting 9 products synched.


3-Deleted the 9 items from "All products"
4-Sync all

Result: Sync bar is reset and counter turned to zero
No last sync date was included

Test Result didn't match the acceptance criteria
@iamdharmesh

**Comment by iamdharmesh** [comment] 2020-12-16 10:13
@suraj-rathod please help to check on this.

**Comment by suraj-rathod** [comment] 2020-12-16 10:43
@iamdharmesh I will check it and let you know

**Comment by suraj-rathod** [comment] 2020-12-17 14:40
@HazemKhaled As Sync bar is reset and counter turned to zero it's not functionality and the last sync date is not used for the display purpose it's used for the backend.

So you have to review an only imported product count same which you imported from the knawat dashboard in settings tab and Sync all functionality will be working in next import time it's only used for the reset the last update date

Please retest it an let me know

**Comment by HeshamIsmail** [comment] 2020-12-18 05:53
As per my test with Suraj:

1-The imported products count is displayed correctly.
2-When you click Sync all the sync bar is not reset, also the number of synced products is not reset.

As per Suraj the last sync date is only resetting in the back end, not the front end.
He also confirmed that the behavior we got during our test is the one required by design and @HazemKhaled aware of it.

Closing this issue.

**Closed by HeshamIsmail** 2020-12-18 05:53 UTC
Labels: enhancement
